version: "3"
services:
  hw6:
    build: .
    # image: ruby:3.0
    # command: bundle
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src
    # depends_on:
    #   - sqlite3
    # env_file:
    #   - .env
    ports:
      - 3000:3000
  # sqlite3:
  #   image: sqlite3:latest
  hw4:
    image: hw4
    command: ruby lib/web/server.rb
    ports:
      - 5678:5678